---
name: semantic-release-rust-binary
description: GitHub Action to semantically release your Rust binary
author: EricCrosson
branding:
  icon: package
  color: orange

# Use a composite action for access to github.action_path
# (which is only supported in composite actions)

inputs:
  targets:
    description: Whitelist of compilation targets to upload GitHub release binaries for. Must be a subset of supported targets.
    required: true
  toolchain:
    description: Rust toolchain specification
    required: false
    default: stable
  binary-name:
    description: The name of your Rust binary
    required: true
  cargo-registry-token:
    description: API token for writing to your cargo registry
  disable-semantic-release-cargo:
    description: Disable semantic-release-cargo in your release flow. Only takes effect if the action semantic-release config is used.
    default: false
  disable-semantic-release-git:
    description: Disable @semantic-release/git in your release flow. Only takes effect if the action semantic-release config is used.
    default: false
  next-version:
    description: Next semantic-release version number
    required: true
  submodules:
    description: Whether to checkout submodules
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Fetch all history and tags for calculating next semantic version
        fetch-depth: 0
        submodules: ${{ inputs.submodules }}

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install is-semantic-release-configured
      uses: EricCrosson/install-github-release-binary@v2
      with:
        targets: |
          EricCrosson/is-semantic-release-configured@v1
          EricCrosson/configure-semantic-release-assets@v1

    # Terminology:
    #
    # - The "host" is the repository calling this action.
    # - The "action" is this action.
    #
    # When we use the action's semantic-release configuration,
    # install node_modules into an ephemeral .semantic-release-action_rust directory.
    # Add this directory and the semantic-release manifest to the global gitignore.
    #
    # This has the following benefits:
    #
    # - @semantic-release/changelog does not try to commit the npm package manifest
    # - cargo does not include git-ignored files in the package upload

    - id: is-semantic-release-configured
      run: |
        : test for semantic-release configuration
        if is-semantic-release-configured; then
          echo "::debug::Detected semantic-release configuration, using host repository's configuration"
          echo "host-configuration=true" >> "$GITHUB_OUTPUT"
          echo "semantic_release=./node_modules/.bin/semantic-release" >> "$GITHUB_ENV"
        else
          echo "::debug::Did not detect semantic-release configuration, using this action's built-in configuration"
          echo "host-configuration=false" >> "$GITHUB_OUTPUT"
          echo "semantic_release=$GITHUB_WORKSPACE/.semantic-release-action_rust/semantic-release-binary/node_modules/.bin/semantic-release" >> "$GITHUB_ENV"
          echo "artifact_dir=$GITHUB_WORKSPACE/.semantic-release-action_rust/dist/" >> "$GITHUB_ENV"
          echo "node_workdir=$GITHUB_WORKSPACE/.semantic-release-action_rust/semantic-release-binary/" >> "$GITHUB_ENV"
          mkdir -p "$GITHUB_WORKSPACE/.semantic-release-action_rust/semantic-release-binary/"
        fi
      shell: bash

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      run: |
        : configure Node.js path
        echo NODE_PATH="$node_workdir${NODE_PATH:+":$NODE_PATH"}" >> "$GITHUB_ENV"
      shell: bash

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      run: |
        : configure git to ignore semantic-release manifest
        mkdir -p "$HOME/.config/git"
        echo "/.releaserc.json" >> "$HOME/.config/git/ignore"
        echo "/.semantic-release-action_rust/" >> "$HOME/.config/git/ignore"
      shell: bash

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      run: |
        : install semantic-release manifest
        cp "${{ github.action_path }}/package.json" "${{ env.node_workdir }}/package.json"
        cp "${{ github.action_path }}/package-lock.json" "${{ env.node_workdir }}/package-lock.json"
        cp ${{ github.action_path }}/.releaserc.json .releaserc.json
        sed -i 's/BINARY_NAME/${{ inputs.binary-name }}/g' .releaserc.json
      shell: bash

    - name: Install is-semantic-release-configured
      if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && (inputs.disable-semantic-release-git == 'true' || inputs.disable-semantic-release-cargo == 'true')
      uses: EricCrosson/install-github-release-binary@v2
      with:
        targets: EricCrosson/configure-semantic-release-manifest@v1

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && inputs.disable-semantic-release-cargo == 'true'
      run: |
        : disable semantic-release-cargo
        configure-semantic-release-manifest --in-place --remove @semantic-release-cargo/semantic-release-cargo
      shell: bash

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && inputs.disable-semantic-release-git == 'true'
      run: |
        : disable @semantic-release/git
        configure-semantic-release-manifest --in-place --remove @semantic-release/git
      shell: bash

    - run: |
        : configure semantic-release assets
        configure-semantic-release-assets --in-place whitelist "${{ inputs.targets }} SHA256SUMS.txt"
      shell: bash

    # If the semantic-release-cargo plugin never runs, the cargo manifest never has its version bumped.
    # Run the prepare step of semantic-release-cargo by invoking its binary directly.
    - name: Install semantic-release-cargo
      if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && inputs.disable-semantic-release-cargo == 'true'
      uses: EricCrosson/install-github-release-binary@v2
      with:
        targets: semantic-release-cargo/semantic-release-cargo@v2

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && inputs.disable-semantic-release-cargo == 'true'
      run: |
        : bump binary version
        semantic-release-cargo --verbose --verbose --verbose prepare ${{ inputs.next-version }}
      shell: bash

    - name: Download release artifacts
      uses: actions/download-artifact@v3
      with:
        path: ${{ env.artifact_dir }}

    - run: |
        : display downloaded release artifacts
        ls -R
      working-directory: ${{ env.artifact_dir }}
      shell: bash

    - run: |
        : combine checksums
        cat **/${{ inputs.binary-name }}-*-SHA256SUM.txt | tee SHA256SUMS.txt
      working-directory: ${{ env.artifact_dir }}
      shell: bash

    - name: Configure Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Cache host npm dependencies
      if: steps.is-semantic-release-configured.outputs.host-configuration == 'true'
      uses: actions/cache@v3
      id: cache-host-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node-host-${{ hashFiles('package.json', 'package-lock.json') }}

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'true' && steps.cache-host-node-modules.outputs.cache-hit != 'true'
      run: |
        : install host npm dependencies
        npm ci --loglevel error
      shell: bash

    - name: Cache action npm dependencies
      if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      uses: actions/cache@v3
      id: cache-action-node-modules
      with:
        path: .semantic-release-action_rust/semantic-release-binary/node_modules
        key: ${{ runner.os }}-node-action-${{ hashFiles('.semantic-release-action_rust/semantic-release-binary/package-lock.json') }}

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && steps.cache-action-node-modules.outputs.cache-hit != 'true'
      run: |
        : install action npm dependencies
        npm ci --ignore-scripts --loglevel error
      working-directory: ${{ env.node_workdir }}
      shell: bash

    - run: |
        : semantic-release
        ${semantic_release}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        CARGO_REGISTRY_TOKEN: ${{ inputs.cargo-registry-token }}
      shell: bash
