---
name: CI

on:
  workflow_call:
    inputs:
      submodules:
        description: Whether to checkout submodules. Use `true` to checkout submodules or `recursive` to recursively checkout submodules -- see https://github.com/actions/checkout
        required: false
        type: string
        default: false
      toolchain:
        description: Rust toolchain specification -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
        required: false
        type: string
        default: stable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.submodules }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check if crate is a library
        id: check-if-crate-is-library
        run: |
          is_crate_library="$(
            cargo read-manifest \
            | jq '.targets | map(.kind) | flatten | map(select(. == "lib")) | length > 0'
          )"
          echo "is-crate-library=$is_crate_library" >> "$GITHUB_OUTPUT"

      # REFACTOR: can use the cargo manifest command to check if this is a library crate,
      # or just check if there is a Cargo.lock file
      - name: Construct test command
        id: format-test-command
        env:
          input_test_command: cargo test --locked -- --nocapture
          is_crate_library: ${{ steps.check-if-crate-is-library.outputs.is-crate-library }}
        run: |
          test_command="$input_test_command"

          # If the user has not overridden the default test command, and this is
          # a library crate, we need to remove the '--locked' argument. This is
          # necessary because library crates do not commit a Cargo.lock file.
          if [[ "$input_test_command" == "cargo test --locked -- --nocapture" && "$is_crate_library" == true ]]; then
            test_command="${input_test_command//--locked }"
          fi
          echo "test-command=$test_command" >> "$GITHUB_OUTPUT"

      # Separate compilation from testing to accurately report the runtime of each
      - run: cargo test ${{ contains(steps.format-test-command.outputs.test-command, '--locked') && '--locked' || '' }} --no-run

      - run: ${{ steps.format-test-command.outputs.test-command }}
