---
name: CI

on:
  workflow_call:
    inputs:
      toolchain:
        description: Rust toolchain specification -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
        required: false
        type: string
        default: stable
      test-command:
        description: Cargo command used to provide confidence in proposed changes
        required: false
        type: string
        default: cargo test --locked -- --nocapture

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        id: rust-toolchain
        with:
          toolchain: ${{ inputs.toolchain }}

      - uses: Swatinem/rust-cache@v2

      # Separate compilation from testing to accurately report the runtime of each
      - if: startsWith(inputs.test-command, 'cargo test')
        run: cargo test --no-run ${{ contains(inputs.test-command, '--locked') && '--locked' || '' }}

      - run: ${{ inputs.test-command }}
