---
name: CI

on:
  workflow_call:
    inputs:
      submodules:
        description: Whether to checkout submodules. Use `true` to checkout submodules or `recursive` to recursively checkout submodules -- see https://github.com/actions/checkout
        required: false
        type: string
        default: false
      toolchain:
        description: Rust toolchain specification -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
        required: false
        type: string
        default: stable
      test-command:
        description: Cargo command used to provide confidence in proposed changes
        required: false
        type: string
        default: cargo test --locked -- --nocapture

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: ${{ inputs.submodules }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        id: rust-toolchain
        with:
          toolchain: ${{ inputs.toolchain }}

      - uses: Swatinem/rust-cache@v2

      # Separate compilation from testing to accurately report the runtime of each
      - if: startsWith(inputs.test-command, 'cargo test')
        run: cargo test ${{ contains(inputs.test-command, '--locked') && '--locked' || '' }} --no-run

      - run: ${{ inputs.test-command }}
