---
name: Release Library

on:
  workflow_call:
    inputs:
      test-command:
        description: Command used to test your Rust program
        type: string
        default: cargo test
      toolchain:
        description: Rust toolchain specification
        type: string
        default: stable
      disable-semantic-release-git:
        description: Disable @semantic-release/git in your release flow. Only takes effect if the action semantic-release config is used.
        type: boolean
        default: true
    secrets:
      cargo-registry-token:
        description: API token for writing to your cargo registry
        required: true

# Only allow one release workflow to execute at a time, since each release
# workflow uses shared resources (git tags, package registries)
concurrency:
  group: ${{ github.workflow }}

env:
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Release
        uses: semantic-release-action/rust/semantic-release-library@v4
        with:
          toolchain: ${{ inputs.toolchain }}
          test-command: ${{ inputs.test-command }}
          disable-semantic-release-git: ${{ inputs.disable-semantic-release-git }}
          cargo-registry-token: ${{ secrets.cargo-registry-token }}
