---
name: Release Binary

on:
  workflow_call:
    inputs:
      toolchain:
        description: Rust toolchain specification -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
        required: false
        type: string
        default: stable
      test-command:
        description: Command used to test your Rust program
        required: false
        type: string
        default: cargo test
      binary-name:
        description: The name of your Rust binary
        required: true
        type: string
    secrets:
      cargo-registry-token:
        description: API token for writing to your cargo registry
        required: true

# Only allow one release workflow to execute at a time, since each release
# workflow uses shared resources (git tags, package registries)
concurrency:
  group: ${{ github.workflow }}

env:
  RUST_BACKTRACE: 1

jobs:
  get-next-version:
    name: Calculate next release
    runs-on: ubuntu-latest
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}

    steps:
      - name: Calculate next semantic-release version
        id: get-next-version
        uses: semantic-release-extras/next-release-version@v1

  test:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        id: rust-toolchain
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Cache cargo
        uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ steps.rust-toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Test
        run: ${{ inputs.test-command }}

  # Compile release artifacts
  build-release:
    name: Build CLI ${{ matrix.build.target }}
    if: needs.get-next-version.outputs.new-release-published == 'true'
    runs-on: ${{ matrix.build.os }}
    needs:
      - get-next-version
    env:
      CARGO: cargo

    strategy:
      fail-fast: false
      matrix:
        build:
          # alphabatized by target
          - os: macOS-latest
            target: aarch64-apple-darwin
            cross: true
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross: true
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            cross: true
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            cross: true
          - os: ubuntu-latest
            target: i686-unknown-linux-musl
            cross: true
          - os: macOS-latest
            target: x86_64-apple-darwin
            cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cross: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install build inputs
        if: runner.os == 'Linux' && !matrix.build.cross && endsWith(matrix.build.target, '-musl')
        run: sudo apt install musl-tools

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        id: rust-toolchain
        with:
          toolchain: nightly
          target: ${{ matrix.build.target }}

      - name: Cache cargo
        uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ steps.rust-toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install semantic-release-cargo
        uses: EricCrosson/install-github-release-binary@v1
        with:
          repo: semantic-release-cargo/semantic-release-cargo@v2

      - name: Prepare semantic-release for Rust
        run: semantic-release-cargo --verbose --verbose --verbose prepare ${{ needs.get-next-version.outputs.new-release-version }}

      - name: Install cross
        uses: taiki-e/install-action@v2
        if: matrix.build.cross
        with:
          tool: cross

      - name: Configure cross
        if: matrix.build.cross
        run: echo "CARGO=cross" >> "$GITHUB_ENV"

      - name: Compile release binary
        run: ${{ env.CARGO }} build --release --target ${{ matrix.build.target }} --verbose

      - name: Create release artifacts
        run: |
          mkdir dist
          cp target/${{ matrix.build.target }}/release/${{ inputs.binary-name }} dist/${{ inputs.binary-name }}-${{ matrix.build.target }}

      - name: Create binary checksum
        run: shasum --algorithm 256 --binary ${{ inputs.binary-name }}-${{ matrix.build.target }} | tee ${{ inputs.binary-name }}-${{ matrix.build.target }}-SHA256SUM.txt
        working-directory: ./dist

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.build.target }}
          path: |
            dist/${{ inputs.binary-name }}-${{ matrix.build.target }}
            dist/${{ inputs.binary-name }}-${{ matrix.build.target }}-SHA256SUM.txt
          if-no-files-found: error
          retention-days: 1

  release:
    name: Release
    if: needs.get-next-version.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    needs:
      - build-release
      - get-next-version
      - test

    steps:
      - name: Release
        uses: EricCrosson/rust-action/semantic-release-binary@v2
        with:
          binary-name: ${{ inputs.binary-name }}
          cargo-registry-token: ${{ secrets.cargo-registry-token }}
